### ISSUE TITLE
Get undefined when loading script

### ISSUE THREAD

**Issue by kjetilh** [Selz/javascript-sdk#12]
I try to load https://sdk.selzstatic.com/1.0.3/client.js in a test web page but get "TypeError: t is undefined" when loading it. I got the url from the documentation.

**Comment by sampotts** [comment]
Hey @kjetilh, can you try the latest version (`2.0.0`)? We need to update the docs. Depending on your setup you might find using it via npm as a module better but anyway, here's the URL:
https://sdk.selzstatic.com/2.0.0/client.js

**Comment by kjetilh** [comment]
Ah - thanks for fast response.
