### ISSUE TITLE
Selz button init

### ISSUE THREAD

**Issue by cyrilpozzo** [Selz/javascript-sdk#17]
Hi there,

Is there a way to init selz button using the javascript sdk? something similar to the code below:

`$.selz({
		theme: {
			button: {
				bg: '#d49a2a',
				text: '#fff',
			},
			checkout: {
				bg: '#d49a2a',
				text: '#fff',
				headerBg: '#d49a2a',
				headerText: '#fff',
			},
		},
		getTracking: $link => {
		},
		onDataReady: ($link, data) => {
			$link.data('modal-url', data.CheckoutUrl);
		},
		onModalOpen: $link => {
		},
		onPurchase: data => {
		},
		onProcessing: data => {
		},
		onClose: ($link, data) => {
		},
	});`

I'm bundling my code with webpack and I don't feel to call the selz scripts & styles from the CDN. What would be the best way to store the scripts? Thank you in advance.

**Comment by woro83c** [comment]
Hey @cyrilpozzo - unfortunately there's no way to do that currently - you'll need to call the script(s) from the CDN.

**Comment by cyrilpozzo** [comment]
Ok thank you @woro83c for this answer :)
