### ISSUE TITLE
Some methods' API seem to expect different params than what is defined in the docs

### ISSUE THREAD

**Issue by kvasimon** [Selz/javascript-sdk#26]
I'm trying to set up a storefront using this SDK, but I'm experiencing some issues with some of the methods.

I'm using `getActiveCart` and `createCart` like this:
```
const res = await client.getActiveCart(false)
```

But I can't get it to work. This is what I get:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (client.mjs?324e:1)
```
Is `getActiveCart` expecting an object param? Or am I just misinterpreting it? Either way, I'm not sure if it corresponds with what it says in the docs.

Also, this SDK doesn't seem to be intended for server-side projects as it expects `window`, but is there a way to get around the CORS issues? I'm using a `Bearer` token on my requests, but it doesn't seem to work with all methods (but with some, it does).

I'm building a store for a very cool project, but with a deadline, so would appreciate help on this 🙏🏻

**Comment by sampotts** [comment]
G'day @kvasimon, 

Sorry, I'd have liked to help get this issues resolved but sadly this project is no longer active and won't be receiving any updates since [our acquisition](https://founderu.selz.com/selz-update/). 

We will be shortly archiving this repo. 

Thanks for your interest.
